# vim: et
---

dev_packages_platform_specific:
  - ansible-lint
  - black
  - python3-pylsp
  - python3-pylsp-black
  - python3-pylsp-rope
  - python3-rope
  - pylint
  - qtcreator
  - screenkey
  - shellcheck
