# vim: et
---

dev_packages_common:
  - ansible
  - ansible-lint
  - make
  - qtcreator
  - screenkey

dev_packages_archlinux:
  - code # VS Code
  - python-lsp-server
  - python-pylint
  - shellcheck
  - unityhub # From AUR

dev_packages_redhat:
  - codium
  - pylint
  - python3-lsp-server
  - ShellCheck
