# vim: et
---

dev_packages_platform_specific:
  - ansible-lint
  - code
  - python-black
  - python-lsp-rope
  - python-pylint
  - python-python-lsp-server
  - python-rope
  - qt-creator
  - screenkey
  - ShellCheck
