# vim: et
---

dev_packages_platform_specific:
  - black
  - codium
  - cppcheck
  - pylint
  - python3-ansible-lint
  - python3-lsp-black
  - python3-lsp-server
  - qtcreator
  - screenkey
  - ShellCheck
