# vim: et
---

- name: Disable IPv6
  become: true
  ansible.builtin.copy:
    src: disable_ipv6.conf
    dest: /etc/sysctl.d/10-disable-ipv6.conf
    owner: root
    group: root
    mode: "0644"
  notify: Load sysctl config
