# vim: et
---

- name: Allow uploading
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^# ?write_enable='
    line: 'write_enable=YES'

- name: Allow local user login
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^# ?local_enable='
    line: 'local_enable=YES'

- name: Allow chrooted user
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^# ?=chroot_local_user='
    line: 'chroot_local_user=YES'
