# vim: et
---

- name: Enable vsftpd
  ansible.builtin.systemd_service:
    name: vsftpd
    enabled: true

- name: Start vsftpd
  ansible.builtin.systemd_service:
    state: started
    name: vsftpd
    daemon_reload: true
