# vim: et

- hosts: localhost
  tasks:

    - name: Install packages for Fedora-based distros
      import_tasks: install_packages_fedora.yml
      become: yes
      when: ansible_facts['os_family']|lower == 'fedora' or
            ansible_facts['os_family']|lower == 'nobara' or
            ansible_facts['os_family']|lower == 'redhat'

    - name: Install packages for Arch-based distros
      import_tasks: install_packages_arch.yml
      become: yes
      when: ansible_facts['os_family']|lower == 'arch' or
            ansible_facts['os_family']|lower == 'manjaro'

    - name: Create Vim plugin directory
      file:
        path: "{{ ansible_env.HOME }}/.vim/autoload"
        state: directory

    - name: Install VimPlug
      get_url:
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

