# vim: et
---

# Communication
- name: Install communication packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - discord

# Dev
- name: Install dev packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - make
    - qtcreator

# Games
- name: Install gaming packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - aisleriot
    - lutris
    - mangohud
    - steam

# Media
- name: Install media packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - pinta
    - strawberry
    - vlc

# Tools (CLI)
- name: Install tools packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - autojump
    - bat
    - git
    - htop
    - neofetch
    - syncthing
    - tmux
    - vim

# Tools (GUI)
- name: Install tools packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - flameshot
    - kde-connect
    - redshift
    - timeshift
    - yakuake
