# vim: et
---

# Install custom repos
- name: Install custom repos
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    mode: 0644
  loop:
    - vscodium.repo

- name: Install packages (communication)
  become: true
  ansible.builtin.package:
    name:
      - discord
    state: present

- name: Install packages (dev)
  become: true
  ansible.builtin.package:
    name:
      - ansible
      - ansible-lint
      - codium
      - make
      - qtcreator
      - ShellCheck
    state: present

- name: Install packages (gaming)
  become: true
  ansible.builtin.package:
    name:
      - aisleriot
      - lutris
      - mangohud
      - steam
    state: present

- name: Install packages (media)
  become: true
  ansible.builtin.package:
    name:
      - pinta
      - strawberry
      - vlc
    state: present

- name: Install packages (CLI tools)
  become: true
  ansible.builtin.package:
    name:
      - autojump
      - bat
      - git
      - htop
      - neofetch
      - nethogs
      - syncthing
      - tmux
      - vim-enhanced
    state: present

- name: Install packages (GUI tools)
  become: true
  ansible.builtin.package:
    name:
      - flameshot
      - kde-connect
      - redshift
      - timeshift
      - vim-X11
      - yakuake
    state: present
