# vim: et
---

- name: Set up workstation
  hosts: localhost

  vars:
    - applications_dir: /usr/share/applications
    - autostart_dir: "{{ ansible_env.HOME }}/.config/autostart"
    - user: namdrib

  roles:
    - common
    - dev
    - desktop
    - gaming
    - mount_network_shares

  tasks:
    - name: Run programs on system startup
      ansible.builtin.import_tasks: start_programs_automatically.yml
