
- hosts: localhost

  vars:
    - git_repo_dir: "{{ ansible_env.HOME }}/coding/git/namdrib"

  tasks:

    - name: Install packages
      import_tasks: install_packages.yml

    - name: Create network shares
      import_tasks: network_shares.yml
