# vim: et
---

- name: Create network share mount points
  become: true
  ansible.builtin.file:
    dest: "{{ network_mount_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ samba_shares }}"

- name: Write Samba network shares to /etc/fstab
  become: true
  ansible.posix.mount:
    src: "{{ samba_host }}/{{ item }}"
    path: "{{ network_mount_dir }}/{{ item }}"
    opts: "rw,vers=3.0,nofail,file_mode=0644,dir_mode=0755,credentials={{ samba_credentials_file }}"
    fstype: cifs
    backup: true
    state: present
  with_items: "{{ samba_shares }}"
