# vim: et
---

- name: Set up workstation
  hosts: desktops

  vars:
    applications_dir: /usr/share/applications
    autostart_dir: "{{ ansible_env.HOME }}/.config/autostart"
    user: namdrib

  roles:
    - role: common
      tags: common
    - role: ssh_agent_user_service
      tags: ssh_agent_user_service
    # - davfs_client
    - role: dev
      tags: dev
    - role: desktop
      tags: desktop
    - role: gaming
      tags: gaming
    - role: latex
      tags: latex
    - role: monitoring
      tags: monitoring
    - role: samba_client
      tags: samba_client
    - role: kde_workstation
      tags: kde_workstation
    - role: disable_ipv6
      tags: disable_ipv6

  tasks:
    - name: Run programs on system startup
      ansible.builtin.import_tasks: start_programs_automatically.yml
