# vim: et
---

- name: Setup specific to triple-coaster, regardless of the distribution
  hosts: triple-coaster

  roles:
    - ssh_agent_user_service
    - pacman
    - triple-coaster
    - twm

- name: Perform common desktop setup
  ansible.builtin.import_playbook: setup_desktops.yml
