# vim: et
---

- name: Setup nas01
  hosts: nas01

  roles:
    - role: disable_ipv6
      tags: disable_ipv6
    - role: monitoring
      tags: monitoring
    - role: smb_scan_server
      tags: smb_scan_server
