# vim: et
---

- name: Setup Linux Game Server Manager server
  hosts: lgsm_servers

  vars:
    - user: namdrib

  roles:
    # - common
    - { role: lgsm_dependencies, become: yes }
    - lgsm_server
