# vim: et
---

- name: Setup Linux Game Server Manager
  hosts: lgsm_servers

  roles:
    # - common
    # Handles one-time configuration, done as root
    - role: lgsm_dependencies
      become: true

    # Handles per-game configuration, done as the game server
    - role: lgsm_server
