# vim: et
---

- name: Set up workstation
  hosts: desktops

  vars:
    - applications_dir: /usr/share/applications
    - autostart_dir: "{{ ansible_env.HOME }}/.config/autostart"
    - user: namdrib

  roles:
    - common
    - davfs_client
    - dev
    - desktop
    - gaming
    - latex
    - samba_client
    - kde_workstation
    - disable_ipv6

  tasks:
    - name: Run programs on system startup
      ansible.builtin.import_tasks: start_programs_automatically.yml
