# vim: et
---

### Root portion
- name: Setup apps01 (root portion)
  become: true
  hosts: apps01

  roles:
    - role: kde_server
      tags: kde_server
    - role: docker
      tags: docker
    - role: monitoring
      tags: monitoring
    - role: nvidia_graphics_drivers
      tags:
        - nvidia
        - drivers
        - graphics
    - role: samba_client
      tags: samba_client

### User portion
- name: Setup apps01 (user portion)
  remote_user: "{{ main_username }}"
  hosts: apps01

  roles:
    - role: common
      tags: common
    - role: server_setup
      tags: server_setup

- name: Setup backups
  hosts: apps01
  roles:
    - role: cronjobs
    - role: fuzzymistborn.autorestic
      become: true
  tags:
    backups

- name: Setup Linux Game Server Manager
  hosts: apps01

  roles:
    # Handles one-time configuration, done as root
    - role: lgsm_dependencies
      become: true

    # Handles per-game configuration, done as the game server
    - role: lgsm_server
  tags:
    lgsm
