# vim: et
---

- name: Setup triple-coaster, regardless of the distribution
  hosts: triple-coaster

  roles:
    - common
    - monitoring
    - kde_workstation
    - ssh_agent_user_service
    - triple-coaster
