# vim: et
---

- name: Install graphics drivers
  hosts: all
  roles:
    - role: intel_graphics_drivers
      tags:
        - intel
        - drivers
        - graphics
    - role: nvidia_graphics_drivers
      tags:
        - nvidia
        - drivers
        - graphics
