# vim: et
---

- name: Setup apps02 (root portion)
  become: true
  hosts: apps02

  roles:
    - kde_server
    - intel_graphics_drivers
    - samba_client

- name: Setup apps02 (user portion)
  remote_user: "{{ main_username }}"
  hosts: apps02

  roles:
    - common
    - server_setup

- name: Setup backups
  hosts: apps02
  roles:
    - role: cronjobs
    - role: fuzzymistborn.autorestic
      become: true
