# vim: et
---

# Includes DHCP reservations
- name: Setup Pi-Hole DNS/DHCP servers
  hosts: piholes

  roles:
    - role: pihole_dns_dhcp_server
      tags: pihole_dns_dhcp_server
    - role: disable_ipv6
      tags: disable_ipv6
