# vim: et
---

# Set the host up for docker operations
# Do not actually pull or start any containers
- name: Setup Docker host
  hosts: dockerhosts

  roles:
    - role: common
      tags: common
    - role: disable_ipv6
      tags: disable_ipv6
    # Some docker functions require network shares
    - role: samba_client
      tags: samba_client
    # Most of the apps are hosted on docker
    # Note: Different distros may have different steps involved
    - role: docker
      tags: docker
    # To make use of the integrated GPU for hardware-accelerated tasks, like
    # transcoding
    # - intel_graphics_drivers
    - role: monitoring
      tags: monitoring
    # Setup the server-setup repo
    - role: server_setup
      tags: server_setup
