# vim: et
---

# Set the host up for docker operations
# Do not actually pull or start any containers
- name: Setup Docker host
  hosts: dockerhosts

  roles:
    - common
    - disable_ipv6
    - docker
