# vim: et
---

- name: Enable SysRq keys
  become: true
  ansible.builtin.copy:
    src: enable-magic-sysrq.conf
    dest: /etc/sysctl.d/90-enable-magic-sysrq.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl config
