---
# tasks file for kde_server

- name: Uninstall packages we don't need
  ansible.builtin.package:
    name: "{{ packages_to_remove }}"
    state: absent

- name: Install packages we want
  ansible.builtin.package:
    name: "{{ packages_to_install }}"
    state: present
