# vim: et
---

# The appdata directory is created in the samba_client role, as that involves
# mounting network shares. If the host needs the appdata directory, it should
# have 'appdata' in the samba_client_extra_mounts host_var

- name: Create config directory
  ansible.builtin.file:
    path: /media/shared/hosting/config
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: '0751'
    state: directory

- name: Create cache directory
  ansible.builtin.file:
    path: /media/shared/hosting/cache
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: '0755'
    state: directory

# This file provides an explanation for the directory structure and information
# on what data should go where
- name: Copy directory structure readme
  ansible.builtin.copy:
    src: README.md
    dest: /media/shared/hosting/
    owner: "{{ main_username }}"
    group: users
    mode: '0644'
