# vim: et
---

dotfiles_repo_url: "git@github.com:Namdrib/dotfiles"
dotfiles_clone_dir: '{{ lookup("env", "HOME") }}/coding/git/namdrib/dotfiles'
dotfiles_install_dir: '{{ lookup("env", "HOME") }}/.dotfiles'

user_config_dir: '{{ lookup("env", "HOME") }}/.config'
