# vim: et
---

- name: Enable COPR repos
  become: true
  become_user: root
  community.general.copr:
    name: "{{ item }}"
    chroot: "fedora-{{ ansible_facts['distribution_major_version'] }}-{{ ansible_facts['architecture'] }}"
  with_items: "{{ twm_copr_repos }}"
