# vim: et
---

- name: Install docker packages (Debian)
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ docker_packages_platform_specific }}"
    state: present
    update_cache: true
