# vim: et
---

__desktop_required_facts:
  - os_family
  - distribution
  - distribution_version

desktop_packages:
  - krdc # Remote desktop application
  - picard
  - putty
  - qbittorrent
  - strawberry
  - vlc
  - yakuake
  - yt-dlp
