# vim: et
---

__twm_required_facts:
  - os_family

# List of packages to install for a workstation with standalone WM
twm_packages:
  - awww # Wallpaper manager
  - darkman # Dark/light settings
  - fuzzel # Application launcher
  - niri # Scrolling window manager
  - playerctl # Control media player actions
  - swayidle # Idle manager
  - swaylock-effects # Lock screen manager (from AUR/COPR)
  - wev # Debug wayland events
  - xwayland-satellite # X application bridge

twm_cursor_dir: /usr/share/icons/breeze_cursors

twm_copr_repos:
  # The chroot needs to be listed here: https://copr.fedorainfracloud.org/coprs/avengemedia/dms/build/9811434/
  - avengemedia/dms # For dms
  - alebastr/sway-extras # For awww
  - eddsalkield/swaylock-effects # For swaylock-effects
