---

# https://docs.pi-hole.net/ftldns/configfile/
- name: Ensure target dirs exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: pihole
    group: pihole
    mode: "0755"
  loop:
    - "{{ pihole_config_dir }}"

- name: Set maximum query age in database
  ansible.builtin.lineinfile:
    path: "{{ pihole_config_dir }}/pihole-FTL.conf"
    regexp: '^MAXDBDAYS='
    line: 'MAXDBDAYS=180'

- name: Ignore localhost queries
  ansible.builtin.lineinfile:
    path: "{{ pihole_config_dir }}/pihole-FTL.conf"
    regexp: '^IGNORE_LOCALHOST='
    line: 'IGNORE_LOCALHOST=yes'
