---

# Note: this playbook should be run with -K and -b to become
# as almost every task needs root or pihole privileges to write files
- name: Check for duplicated items
  ansible.builtin.include_tasks: check_duplicates.yml

- name: Template config files into place
  ansible.builtin.include_tasks: populate_templates.yml
