# vim: et
---

- name: Revoke existing leases if dhcpd file changed (delete)
  become: true
  ansible.builtin.file:
    path: "{{ pihole_config_dir }}/dhcp.leases"
    state: absent
  # when: dhcp_changed.changed

- name: Revoke existing leases if dhcpd file changed (re-create)
  become: true
  ansible.builtin.file:
    path: "{{ pihole_config_dir }}/dhcp.leases"
    state: touch
    owner: pihole
    group: pihole
    mode: "0644"
  # when: dhcp_changed.changed
