# vim: et
---

- name: Install Intel graphics drivers (Arch Linux)
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ intel_graphics_drivers_archlinux }}"
