# vim: et
---

# These tasks all need to be run as root
# The tasks in lgsm_server need to be run as the service user for that server
# Those users are set up by this task
- name: Create users for LGSM
  ansible.builtin.import_tasks: create_game_server_users.yml

- name: Add dpkg architectures
  ansible.builtin.import_tasks: dpkg_add_i386_architecture.yml

- name: Install LGSM dependencies
  ansible.builtin.import_tasks: install_lgsm_dependencies.yml
