# vim: et
---

# See: https://rpmfusion.org/keys
- name: Install RPM Fusion GPG Keys
  become: true
  become_user: root
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop: "{{ rpm_fusion_gpg_keys }}"

# See: https://rpmfusion.org/Configuration
- name: Enable RPM Fusion
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ rpm_fusion_packages_fedora }}"
    state: present
  notify: Update core group
