# vim: et
---

- name: Create monitoring sudoers template
  become: true
  ansible.builtin.template:
    src: monitoring.j2
    dest: /etc/sudoers.d/monitoring
    mode: '0600'
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s
