# vim: et
---

lgsm_games:
  - insserver
  - inssserver

# inssserver template secrets
inssserver_game_ini_rcon_password: "{{ vault_inssserver_game_ini_rcon_password }}"
inssserver_game_ini_rcon_listenport: "{{ vault_inssserver_game_ini_rcon_listenport }}"

# Config files for inssserver
inssserver_files:
  - { source: Admins.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }
  - { source: MapCycleDay.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }
  - { source: MapCycleNight.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }
  - { source: MapCycle-Insurgents.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }
  - { source: MapCycle-Security.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }
  - { source: MapCycle.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }
  - { source: common.cfg, dest: /home/inssserver/lgsm/config-lgsm/inssserver/ }

# Template files for inssserver
inssserver_templates:
  - { source: Game.ini.j2, dest: /home/inssserver/serverfiles/Insurgency/Saved/Config/LinuxServer/Game.ini }
  - { source: inssserver.cfg.j2, dest: /home/inssserver/lgsm/config-lgsm/inssserver/inssserver.cfg }
