# vim: et
---

lgsm_games:
  - insserver
  - inssserver

# Create a password for each LGSM user
# Each LGSM game server should have a corresponding user with the same name (and password)
# To add a new game server, add a new line here, and a new vault entry for the password
lgsm_users:
  - { name: insserver, password: "{{ vault_insserver_password }}" }
  - { name: inssserver, password: "{{ vault_inssserver_password }}" }

# insserver template secrets
insserver_rcon_password: "{{ vault_insserver_rcon_password }}"
insserver_sv_password: "{{ vault_insserver_sv_password }}"

# inssserver template secrets
inssserver_game_ini_rcon_password: "{{ vault_inssserver_game_ini_rcon_password }}"
inssserver_game_ini_rcon_listenport: "{{ vault_inssserver_game_ini_rcon_listenport }}"

# Config files for insserver
insserver_files:
  - { source: insserver.cfg, dest: /home/insserver/lgsm/config-lgsm/insserver/ }

insserver_templates:
  - { source: insserver.cfg.j2, dest: /home/insserver/serverfiles/insurgency/cfg/insserver.cfg }

# Config files for inssserver
inssserver_files:
  - { source: Admins.txt, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/ }

inssserver_templates:
  - { source: Game.ini.j2, dest: /home/inssserver/serverfiles/Insurgency/Saved/Config/LinuxServer/Game.ini }
  - { source: MapCycle.txt.j2, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/MapCycle.txt }
  - { source: MapCycleDay.txt.j2, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/MapCycleDay.txt }
  - { source: MapCycleNight.txt.j2, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/MapCycleNight.txt }
  - { source: MapCycle-Insurgents.txt.j2, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/MapCycle-Insurgents.txt }
  - { source: MapCycle-Security.txt.j2, dest: /home/inssserver/serverfiles/Insurgency/Config/Server/MapCycle-Security.txt }
  - { source: inssserver.cfg.j2, dest: /home/inssserver/lgsm/config-lgsm/inssserver/inssserver.cfg }

# A list of scenarios to include in the server map rotation
# These are inserted into the MapCycle templates
inssserver_scenarios:
  - Bab
  - Citadel
  - Crossing
  - Farmhouse
  - Gap
  - Hideout
  - Hillside
  - LastLight
  - Ministry
  - Outskirts
  - PowerPlant
  - Precinct
  - Prison
  - Refinery
  - Summit
  - Tell
  - Tideway
  - Trainyard
