# vim: et
---

- name: Reload fstab
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Update grub
  become: true
  become_user: root
  ansible.builtin.command: update-grub
