# vim: et
---

# Credentials
samba_client_username: "{{ vault_samba_client_username }}"
samba_client_password: "{{ vault_samba_client_password}}"
samba_client_groupname: users
samba_credentials_file: /root/.smbcredentials

# Mount configuration
samba_client_mount_dir: /media/shared
samba_client_server: "//{{ samba_host_name }}"
samba_client_mounts:
  # Guest share not included in normal shares
  # There is a separate task to add it
  - images
  - media
  - namdrib
  - security-footage
  - share
  - software
