# vim: et
---

# Credentials
samba_client_username: "{{ vault_samba_client_username }}"
samba_client_password: "{{ vault_samba_client_password }}"
samba_client_groupname: users
samba_client_credentials_file: /root/.smbcredentials

# Mount configuration
samba_client_mount_dir: "{{ mount_point }}"
samba_client_server: "//{{ samba_host_name }}"
samba_client_mounts:
  # Guest share not included in normal shares
  # There is a separate task to add it
  - namdrib
  - share

# Start off empty, each host should add to the list depending on what they need
# Each entry should correspond to one of the variables below, which provides a
# list of extra mounts to mount
samba_client_extra_mounts: []

samba_client_image_mounts:
  - images

samba_client_media_mounts:
  - media

samba_client_scan_mounts:
  - scans

samba_client_security_footage_mounts:
  - security-footage

samba_client_software_mounts:
  - software

# Verify that no mounts is valid
samba_client_empty_mounts: []
