# vim: et
---

network_mount_dir: /media/shared
samba_credentials_file: /root/.smbcredentials
samba_host: "//{{ samba_host_name }}"
samba_shares:
  # Guest share not included in normal shares
  # There is a separate task to add it
  - images
  - media
  - namdrib
  - share
  - software
