# vim: et
---

network_mount_dir: /media/shared
samba_credentials_file: /root/.smbcredentials
samba_host: "//{{ samba_host_ip }}"
samba_shares:
  - guest
  - images
  - media
  - namdrib
  - share
  - software
