# vim: et
---

# For more details, see: https://github.com/chaotic-aur
- name: Install Chaotic AUR primary key
  become: true
  ansible.builtin.command: pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
  register: key_install
  changed_when: '"not changed" not in key_install.stderr'

- name: Debug installing Chaoric AUR primary key
  ansible.builtin.debug:
    msg: "{{ key_install.stderr }}"

- name: Sign the Chaotic AUR primary key
  become: true
  ansible.builtin.command: pacman-key --lsign-key 3056513887B78AEB
  register: key_sign
  changed_when: '"Locally signed" in key_sign.stderr'

- name: Debug signing Chaoric AUR primary key
  ansible.builtin.debug:
    msg: "{{ key_sign.stderr }}"

- name: Install Chaoric AUR packages
  become: true
  ansible.builtin.command: pacman -U --noconfirm --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
  register: aur_packages
  changed_when: '"nothing to do" not in aur_packages.stdout'

- name: Debug installing Chaoric AUR packages
  ansible.builtin.debug:
    msg: "{{ aur_packages.stdout }}"

- name: Install AUR packages
  become: true
  ansible.builtin.package:
    name:
      - yay
    state: present

- name: Set up pacman.conf - Add chaoric AUR mirror list
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
    owner: root
    group: root
    mode: '0644'
