# vim: et
---

- name: Set up pacman.conf - Colour
  become: true
  community.general.ini_file:
    path: /etc/pacman.conf
    section: options
    option: Color
    allow_no_value: true
    mode: '0644'

- name: Set up pacman.conf - Eye Candy
  become: true
  community.general.ini_file:
    path: /etc/pacman.conf
    section: options
    option: ILoveCandy
    allow_no_value: true
    mode: '0644'

- name: Set up pacman.conf - Check Space
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '#?CheckSpace'
    line: CheckSpace
    owner: root
    group: root
    mode: '0644'
