# vim: et
---

# Build the list of network mounts that should be set up, depending on
# attributes of the host
# That way, it starts off minimal, and the shares that are required are added
# as-needed
- name: Add image mounts, if applicable
  ansible.builtin.set_fact:
    samba_client_mounts: "{{ samba_client_mounts + samba_client_image_mounts }}"
  # when: mounts_images
  when: "'images' in extra_mounts"

- name: Add media mounts, if applicable
  ansible.builtin.set_fact:
    samba_client_mounts: "{{ samba_client_mounts + samba_client_media_mounts }}"
  # when: mounts_media
  when: "'media' in extra_mounts"

- name: Add scan mounts, if applicable
  ansible.builtin.set_fact:
    samba_client_mounts: "{{ samba_client_mounts + samba_client_scan_mounts }}"
  # when: mounts_scans
  when: "'scans' in extra_mounts"

- name: Add security footage mounts, if applicable
  ansible.builtin.set_fact:
    samba_client_mounts: "{{ samba_client_mounts + samba_client_security_footage_mounts }}"
  when: "'security-footage' in extra_mounts"

- name: Add software mounts, if applicable
  ansible.builtin.set_fact:
    samba_client_mounts: "{{ samba_client_mounts + samba_client_software_mounts }}"
  when: "'software' in extra_mounts"

- name: Add empty mounts, if applicable
  ansible.builtin.set_fact:
    samba_client_mounts: "{{ samba_client_mounts + samba_client_empty_mounts }}"

- name: Print mounts list
  ansible.builtin.debug:
    var: samba_client_mounts
