# vim: et
---

# This same file will be used by the non-guest samba fstab entries
- name: Create the smbcredentials file from template
  become: true
  become_user: root
  ansible.builtin.template:
    src: smbcredentials.j2
    dest: "{{ samba_client_credentials_file }}"
    owner: root
    group: root
    mode: '0600'
