# vim: et
---

- name: Create network share mount points
  become: true
  become_user: root
  ansible.builtin.file:
    dest: "{{ samba_client_mount_dir }}/{{ item }}"
    state: directory
    owner: "{{ samba_client_username }}"
    group: "{{ samba_client_groupname }}"
    mode: '0755'
  with_items: "{{ samba_client_mounts }}"

- name: Write Samba network shares to /etc/fstab
  become: true
  become_user: root
  ansible.posix.mount:
    src: "{{ samba_client_server }}/{{ item }}"
    path: "{{ samba_client_mount_dir }}/{{ item }}"
    opts: "vers=3,nofail,auto,x-systemd.automount,credentials={{ samba_client_credentials_file }},uid={{ samba_client_username }},gid={{ samba_client_groupname }}"
    fstype: cifs
    backup: true
    state: present
  with_items: "{{ samba_client_mounts }}"
  notify: Reload fstab

- name: Write Samba guest share to /etc/fstab
  become: true
  become_user: root
  ansible.posix.mount:
    src: "{{ samba_client_server }}/guest"
    path: "{{ samba_client_mount_dir }}/guest"
    opts: "vers=3,nofail,auto,x-systemd.automount,guest,uid={{ samba_client_username }},gid={{ samba_client_groupname }}"
    fstype: cifs
    backup: true
    state: present
  when: "'guest' in extra_mounts"
  notify: Reload fstab
