# vim: et
---

# Network drives are handled by the samba_client role
# This needs to be done before the symlinks, as some symlinks run across
# multiple drives
- name: Mount local drives
  ansible.builtin.import_tasks: mount_local_drives.yml

- name: Create XDG symlinks which are used by the shared symlinks
  ansible.builtin.import_tasks: create_xdg_symlinks.yml

- name: Create shared symlinks
  ansible.builtin.import_tasks: create_shared_symlinks.yml

- name: Create user symlinks
  ansible.builtin.import_tasks: create_user_symlinks.yml

- name: Set kernel boot parameters
  ansible.builtin.import_tasks: set_kernel_boot_parameters.yml
