# vim: et
---

# This same file will be used by the non-guest samba fstab entries
- name: Set perms on credentials file
  become: true
  ansible.builtin.file:
    path: "{{ samba_credentials_file }}"
    state: file
    mode: '0600'
    owner: root
    group: root
