# vim: et
---

- name: Create network share mount points
  become: true
  become_user: root
  ansible.builtin.file:
    dest: "{{ network_mount_dir }}/{{ item }}"
    state: directory
    owner: "{{ mount_username }}"
    group: "{{ mount_groupname }}"
    mode: '0755'
  with_items: "{{ samba_shares }}"

- name: Write Samba network shares to /etc/fstab
  become: true
  become_user: root
  ansible.posix.mount:
    src: "{{ samba_host }}/{{ item }}"
    path: "{{ network_mount_dir }}/{{ item }}"
    opts: "vers=3,nofail,auto,x-systemd.automount,credentials={{ samba_credentials_file }},uid={{ mount_username }},gid={{ mount_groupname }}"
    fstype: cifs
    backup: true
    state: present
  with_items: "{{ samba_shares }}"

- name: Write Samba guest share to /etc/fstab
  become: true
  become_user: root
  ansible.posix.mount:
    src: "{{ samba_host }}/guest"
    path: "{{ network_mount_dir }}/guest"
    opts: "vers=3,nofail,auto,x-systemd.automount,guest,uid={{ mount_username }},gid={{ mount_groupname }}"
    fstype: cifs
    backup: true
    state: present
