# vim: et
---

# Because the src doesn't have a trailing slash, the entire directory _and_ its
# contents are copied
- name: Copy all powerline config files into user's config directory
  ansible.posix.synchronize:
    src: powerline
    dest: "{{ user_config_dir }}/"
  notify: 'Reload powerline daemon'
