# vim: et
---

- name: Create powerline user customisation dirs
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  loop:
    - "{{ powerline_shell_theme_dir }}"

- name: Set powerline main shell theme file
  ansible.builtin.copy:
    src: powerline/shell_theme_file.json
    dest: "{{ powerline_shell_theme_dir }}/__main__.json"
    mode: '0644'
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
