# vim: et
---

- name: Install common packages (fedora)
  become: true
  ansible.builtin.package:
    name:
      - dnf-plugins-core
      - plocate
      - vim-X11
      - vim-enhanced
    state: present
