# vim: et
---

- name: Make sure git is installed
  package:
    name: git
    state: present

- name: Fetch fzf from GitHub
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ ansible_env.HOME }}/.fzf"
    version: HEAD # latest

- name: Run install script
  script: "{{ ansible_env.HOME}}/.fzf/install --key-bindings --no-completion --no-update-rc"
