# vim: et
---

- name: Make sure git is installed
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Fetch fzf from GitHub
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "/tmp/fzf"
    # dest: "{{ ansible_env.HOME }}/.fzf"
    version: HEAD # latest

# This installs from a tmp (ansible) location, and so the dot files point to broken locations
# - name: Run install script
#   script: "/tmp/fzf/install --key-bindings --no-completion --no-update-rc"
