# vim: et
---

- name: Install common packages (arch)
  become: true
  ansible.builtin.package:
    name:
      - bitwarden
      - gvim # provides CLI vim as well
      - kdeconnect
      - obsidian
    state: present
