# vim: et
---

- name: Create git repo area
  ansible.builtin.file:
    path: "{{ git_repo_dir }}"
    state: directory
    mode: '0755'

- name: Clone dotfiles repo
  ansible.builtin.git:
    dest: "{{ git_repo_dir }}/dotfiles"
    repo: "{{ dotfiles_repo_url }}"
    update: true

- name: Symlink the dotfiles repo to ~/.dotfiles
  ansible.builtin.file:
    src: "{{ git_repo_dir }}/dotfiles"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    state: link
    force: true
    mode: '0755'

- name: Install the dotfiles
  ansible.builtin.script: "{{ ansible_env.HOME }}/.dotfiles/install.sh"
