# vim: et
---

- name: Create git repo area
  ansible.builtin.file:
    path: "{{ dotfiles_clone_dir }}"
    state: directory
    mode: '0750'

- name: Clone dotfiles repo
  ansible.builtin.git:
    dest: "{{ dotfiles_clone_dir }}"
    repo: "{{ dotfiles_repo_url }}"
    accept_newhostkey: true
    update: false

- name: Symlink the dotfiles repo to ~/.dotfiles
  ansible.builtin.file:
    src: "{{ dotfiles_clone_dir }}"
    dest: "{{ dotfiles_install_dir }}"
    state: link
    force: true
    mode: '0750'

- name: Install the dotfiles
  ansible.builtin.script: "{{ dotfiles_install_dir }}/install.sh"
