# vim: et
---

# Assumes the host runs Ubuntu. TODO: Make more generic
# Consider https://github.com/NVIDIA/ansible-role-nvidia-driver
- name: Install Nvidia drivers
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: "ubuntu-drivers install {{ nvidia_graphics_drivers_version }}"
