# vim: et
---

# https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
- name: Install dependencies
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create keyrings directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: '0755'

- name: Download Linux GPG key
  become: true
  become_user: root
  ansible.builtin.get_url:
    # I've confirmed the Ubuntu and Debian keys are the same
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add repo to apt sources (Debian)
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    # using arch={{ ansible_architecture }} gives the wrong result (x86_64)
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
