# vim: et
---

- name: Nothing to do here, using default packages
  ansible.builtin.debug:
    msg: 'Nothing to do here, using default packages. See the redhat file if the Docker package is preferred'

# - name: Check whether Docker repo exist
#   ansible.builtin.command:
#     cmd: 'dnf repolist'
#   register: repolist
#   changed_when: false

# - name: Add docker DNF repo (RedHat)
#   become: true
#   become_user: root
#   ansible.builtin.command:
#     cmd: "dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo"
#   register: add_docker_repo
#   changed_when: '"already exists" not in add_docker_repo.stderr'
#   when: "'docker-ce-stable' not in repolist.stdout"
