# vim: et
---

# Samba shares
# For paperless, nextcloud, starr
samba_client_extra_mounts: ['appdata', 'media', 'scans', 'software']

# Cronjobs
cronjobs:
  - name: Restic Backups (Docker Nextcloud stack)
    # Only run on Sunday mornings to not be disruptive
    # Should probably do the nextcloud db too
    job: /usr/local/bin/autorestic backup -l nextcloud_appdata -l nextcloud_config -c /home/{{ main_username }}/.autorestic.yml
    user: "{{ main_username }}"
    minute: 0
    hour: 6
    weekday: 0

  - name: Restic Backups (Docker starr stack)
    job: /usr/local/bin/autorestic backup -l bazarr_backups -l lidarr_backups -l lms_config -l ombi_config -l prowlarr_backups -l radarr_backups -l readarr_backups -l sonarr_backups -c /home/{{ main_username }}/.autorestic.yml
    user: "{{ main_username }}"
    minute: 30
    hour: 2
    weekday: 2,4

  - name: Restic Backups (Docker appdata)
    job: /usr/local/bin/autorestic backup -l paperless_appdata -l smokeping_appdata -l syncthing_appdata -c /home/{{ main_username }}/.autorestic.yml
    user: "{{ main_username }}"
    minute: 0
    hour: 2
    weekday: 2,4

  - name: Restic Backups (Docker configs)
    job: /usr/local/bin/autorestic backup -l authelia_config -c /home/{{ main_username }}/.autorestic.yml
    user: "{{ main_username }}"
    minute: 15
    hour: 2
    weekday: 2,4

# Backup configuration
autorestic_config_user: "{{ main_username }}"
autorestic_user_directory: "/home/{{ main_username }}"
autorestic_config_yaml:
  version: 2
  backends:
    nas_nextcloud_appdata:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/nextcloud_appdata"
      key: "{{ restic_repo_key }}"
    nas_paperless_appdata:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/paperless_appdata"
      key: "{{ restic_repo_key }}"
    nas_smokeping_appdata:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/smokeping_appdata"
      key: "{{ restic_repo_key }}"
    nas_syncthing_appdata:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/syncthing_appdata"
      key: "{{ restic_repo_key }}"

    nas_authelia_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/authelia_config"
      key: "{{ restic_repo_key }}"
    nas_frigate_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/frigate_config"
      key: "{{ restic_repo_key }}"
    nas_nextcloud_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/nextcloud_config"
      key: "{{ restic_repo_key }}"
    nas_photoprism_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/photoprism_config"
      key: "{{ restic_repo_key }}"

    nas_bazarr_backups:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/bazarr_backups"
      key: "{{ restic_repo_key }}"
    nas_lidarr_backups:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/lidarr_backups"
      key: "{{ restic_repo_key }}"
    nas_lms_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/lms_config"
      key: "{{ restic_repo_key }}"
    nas_ombi_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/ombi_config"
      key: "{{ restic_repo_key }}"
    nas_prowlarr_backups:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/prowlarr_backups"
      key: "{{ restic_repo_key }}"
    nas_qbittorrent_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/qbittorrent_config"
      key: "{{ restic_repo_key }}"
    nas_radarr_backups:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/radarr_backups"
      key: "{{ restic_repo_key }}"
    nas_readarr_backups:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/readarr_backups"
      key: "{{ restic_repo_key }}"
    nas_sonarr_backups:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/{{ inventory_hostname }}/docker/sonarr_backups"
      key: "{{ restic_repo_key }}"

  locations:
    nextcloud_appdata:
      from: '{{ docker_appdata_dir }}/nextcloud'
      to:
        - nas_nextcloud_appdata
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    paperless_appdata:
      from: '{{ docker_appdata_dir }}/paperless'
      to:
        - nas_paperless_appdata
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    smokeping_appdata:
      from: '{{ docker_appdata_dir }}/smokeping'
      to:
        - nas_smokeping_appdata
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    syncthing_appdata:
      from: '{{ docker_appdata_dir }}/syncthing-consume'
      to:
        - nas_syncthing_appdata
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1

    authelia_config:
      from: '{{ docker_config_dir }}/authelia'
      to:
        - nas_authelia_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    frigate_config:
      from: '{{ docker_config_dir }}/frigate'
      to:
        - nas_frigate_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
        backup:
          exclude:
            - 'model_cache' # This will be re-generated if it doesn't exist
    nextcloud_config:
      from: '{{ docker_config_dir }}/nextcloud'
      to:
        - nas_authelia_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
        backup:
          exclude:
            - 'www/nextcloud/apps'
    photoprism_config:
      from: '{{ docker_config_dir }}/photoprism'
      to:
        - nas_photoprism_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
        backup:
          exclude:
            # This contains thumbnails. No point in backing up
            - 'cache/thumbnails'

    # Mediastraming backups
    bazarr_backups:
      from: '{{ docker_config_dir }}/bazarr/backup'
      to:
        - nas_bazarr_backups
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    lidarr_backups:
      from: '{{ docker_config_dir }}/lidarr/Backups'
      to:
        - nas_lidarr_backups
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    lms_config:
      from: '{{ docker_config_dir }}/lms'
      to:
        - nas_lms_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
        backup:
          exclude:
            - 'cache'
    ombi_config:
      from: '{{ docker_config_dir }}/ombi'
      to:
        - nas_ombi_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
        backup:
          exclude:
            - 'Logs'
    prowlarr_backups:
      from: '{{ docker_config_dir }}/prowlarr/Backups'
      to:
        - nas_prowlarr_backups
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    radarr_backups:
      from: '{{ docker_config_dir }}/radarr/Backups'
      to:
        - nas_radarr_backups
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    readarr_backups:
      from: '{{ docker_config_dir }}/readarr/Backups'
      to:
        - nas_readarr_backups
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
    sonarr_backups:
      from: '{{ docker_config_dir }}/sonarr/Backups'
      to:
        - nas_sonarr_backups
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1
