# vim: et
---

main_username: bunny

# Cronjobs
cronjobs:
  - name: Restic Backups (Media)
    job: /usr/local/bin/autorestic backup -l pihole -c /home/{{ main_username }}/.autorestic.yml
    user: "{{ main_username }}"
    minute: 15
    hour: 1
    weekday: 0,3,5


# Backup configuration
autorestic_config_user: "{{ main_username }}"
autorestic_user_directory: "/home/{{ main_username }}"
autorestic_config_yaml:
  version: 2
  backends:
    nas_pihole_config:
      type: sftp
      path: "{{ samba_host_name }}:{{ restic_backup_dir }}/bomb/pihole"
      key: "{{ restic_repo_key }}"

  locations:
    pihole:
      from: '/etc/pihole'
      to:
        - nas_pihole_config
      options:
        forget:
          keep-daily: 2
          keep-weekly: 3
          keep-monthly: 3
          keep-yearly: 1

autorestic_distro: linux_arm64
restic_distro: linux_arm64
