# vim: et
---

- name: Install packages (dev)
  become: true
  ansible.builtin.package:
    name:
      - ansible
      - ansible-lint
      - make
      - qtcreator
      - screenkey
    state: present
