# vim: et
---

- name: Settings - Highlight Non Default Settings
  community.general.ini_file:
    path: "{{ ansible_env.HOME }}/.config/systemsettingsrc"
    section: systemsettings_sidebar_mode
    option: HighlightNonDefaultSettings
    value: 'true'
    no_extra_spaces: true
    mode: '0644'

- name: Settings - Don't pause media players on sleep
  community.general.ini_file:
    path: "{{ ansible_env.HOME }}/.config/powerdevilrc"
    section: 'General'
    option: pausePlayersOnSuspend
    value: 'false'
    no_extra_spaces: true
    mode: '0644'
