# vim: et
---

# Unsure whether the value of the GUID has any significance
- name: Set virtual desktop IDs and names in kwinrc
  community.general.ini_file:
    path: "{{ ansible_env.HOME }}/.config/kwinrc"
    section: Desktops
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: '0644'
  loop:
    - { key: Id_1, value: 58ce3089-e05a-4380-ab0f-0600630ad22c }
    - { key: Id_2, value: 5b991997-e033-4c3b-a45d-43ce44c7a7a1 }
    - { key: Id_3, value: ad20c38e-b861-446d-9200-e5cedaea8776 }
    - { key: Id_4, value: d04c953c-f0a7-41be-9fdb-0a8195299e38 }
    - { key: Name_1, value: Main }
    - { key: Name_2, value: Comms }
    - { key: Name_3, value: Browsing }
    - { key: Name_4, value: Misc }
    - { key: Number, value: 4 }
    - { key: Rows, value: 2 }
