# vim: et
---

- name: Create users for LGSM
  ansible.builtin.import_tasks: create_game_server_users.yml

- name: Add dpkg architectures
  ansible.builtin.import_tasks: dpkg_add_i386_architecture.yml

- name: Install LGSM dependencies
  ansible.builtin.import_tasks: install_lgsm_dependencies.yml

# - name: Install LGSM server
#   ansible.builtin.include_tasks: install_lgsm_server.yml
#   loop: "{{ lgsm_games }}"

- name: Apply insserver config files
  ansible.builtin.include_tasks: apply_inssserver_config_files.yml

- name: Start the server
  ansible.builtin.include_tasks: start_lgsm_server.yml
  loop:
    - inssserver
