# vim: et
---

- name: Create users for LGSM
  ansible.builtin.import_tasks: create_game_server_users.yml

- name: Add dpkg architectures
  ansible.builtin.import_tasks: dpkg_add_i386_architecture.yml

- name: Install LGSM dependencies
  ansible.builtin.import_tasks: install_lgsm_dependencies.yml

# - name: Install LGSM server
#   ansible.builtin.include_tasks: install_lgsm_server.yml
#   loop: "{{ lgsm_games }}"

# If the server is already running, starting it will wipe Game.ini
# which is placed in the next step
- name: Stop the server
  ansible.builtin.include_tasks: stop_lgsm_server.yml
  loop:
    - inssserver

- name: Apply insserver config files
  ansible.builtin.include_tasks: apply_inssserver_config_files.yml

- name: Insert cron jobs for the server
  ansible.builtin.include_tasks: add_lgsm_cron_job.yml
  loop:
    - inssserver

- name: Start the server
  ansible.builtin.include_tasks: start_lgsm_server.yml
  loop:
    - inssserver
