# vim: et
---

- name: Enable IPv4 forwarding
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.d/99-sysctl.conf"
    regexp: '^#?net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
  notify: sysctl file changed

- name: Enable IPv6 forwarding
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.d/99-sysctl.conf"
    regexp: '^#?net.ipv6.conf.all.forwarding'
    line: 'net.ipv6.conf.all.forwarding=1'
  notify: sysctl file changed
