# vim: et
---

- name: Enable wg0
  become: true
  ansible.builtin.systemd_service:
    name: wg-quick@wg0
    enabled: true

- name: Start wg0
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: wg-quick@wg0
    daemon_reload: true
